// WijnSpijs — dataset met wijnen, gerechten en recepten.
// Het koppelmodel werkt met gedeelde "pairing tags" die zowel bij wijnen
// als bij gerechten voorkomen. Hoe meer overlap, hoe beter de combinatie.

// Pairing tags (categorieën waarop wijn en spijs elkaar vinden):
//  rood-vlees, gevogelte, wild, vis-mager, vis-vet, schaaldieren,
//  kaas-zacht, kaas-pittig, pasta, pittig, kruidig, romig, gegrild,
//  vegetarisch, dessert, aperitief, zomers, hartig

const WINES = [
  {
    id: 'cabernet-sauvignon',
    name: 'Cabernet Sauvignon',
    type: 'Rood',
    druif: 'Cabernet Sauvignon',
    body: 'Vol',
    kenmerken: ['stevige tannines', 'zwarte bes', 'cederhout'],
    omschrijving: 'Krachtige, tanninerijke rode wijn die vraagt om stevig vlees.',
    pairsWith: ['rood-vlees', 'wild', 'gegrild', 'kaas-pittig', 'hartig'],
  },
  {
    id: 'pinot-noir',
    name: 'Pinot Noir',
    type: 'Rood',
    druif: 'Pinot Noir',
    body: 'Licht tot medium',
    kenmerken: ['rood fruit', 'aardetonen', 'soepele tannines'],
    omschrijving: 'Elegante, soepele rode wijn die verrassend veelzijdig combineert.',
    pairsWith: ['gevogelte', 'wild', 'vis-vet', 'kaas-zacht', 'paddenstoelen', 'rood-vlees'],
  },
  {
    id: 'merlot',
    name: 'Merlot',
    type: 'Rood',
    druif: 'Merlot',
    body: 'Medium tot vol',
    kenmerken: ['rijp pruimenfruit', 'zachte tannines', 'fluweel'],
    omschrijving: 'Ronde, toegankelijke rode wijn met zachte tannines.',
    pairsWith: ['rood-vlees', 'gevogelte', 'pasta', 'kaas-zacht', 'hartig', 'gegrild'],
  },
  {
    id: 'syrah',
    name: 'Syrah / Shiraz',
    type: 'Rood',
    druif: 'Syrah',
    body: 'Vol',
    kenmerken: ['zwarte peper', 'donker fruit', 'kruidig'],
    omschrijving: 'Krachtige, peperige wijn die goed tegen specerijen kan.',
    pairsWith: ['rood-vlees', 'gegrild', 'kruidig', 'wild', 'hartig'],
  },
  {
    id: 'chianti',
    name: 'Chianti (Sangiovese)',
    type: 'Rood',
    druif: 'Sangiovese',
    body: 'Medium',
    kenmerken: ['kers', 'frisse zuren', 'kruiden'],
    omschrijving: 'Frisse Italiaanse rode wijn, gemaakt voor tomatensauzen.',
    pairsWith: ['pasta', 'pizza', 'rood-vlees', 'kruidig', 'hartig'],
  },
  {
    id: 'chardonnay',
    name: 'Chardonnay (houtgerijpt)',
    type: 'Wit',
    druif: 'Chardonnay',
    body: 'Vol',
    kenmerken: ['boter', 'vanille', 'rijp geel fruit'],
    omschrijving: 'Volle, romige witte wijn met houttonen.',
    pairsWith: ['gevogelte', 'vis-vet', 'schaaldieren', 'romig', 'kaas-zacht'],
  },
  {
    id: 'sauvignon-blanc',
    name: 'Sauvignon Blanc',
    type: 'Wit',
    druif: 'Sauvignon Blanc',
    body: 'Licht',
    kenmerken: ['frisse zuren', 'kruidig groen', 'citrus'],
    omschrijving: 'Knisperend frisse witte wijn met groene, kruidige toets.',
    pairsWith: ['vis-mager', 'schaaldieren', 'vegetarisch', 'kaas-zacht', 'zomers', 'aperitief'],
  },
  {
    id: 'riesling',
    name: 'Riesling (halfdroog)',
    type: 'Wit',
    druif: 'Riesling',
    body: 'Licht',
    kenmerken: ['restzoet', 'hoge zuren', 'limoen'],
    omschrijving: 'Fris-zoete wijn die pittige en kruidige keukens temt.',
    pairsWith: ['pittig', 'kruidig', 'vis-mager', 'aziatisch', 'gevogelte', 'aperitief'],
  },
  {
    id: 'pinot-grigio',
    name: 'Pinot Grigio',
    type: 'Wit',
    druif: 'Pinot Grigio',
    body: 'Licht',
    kenmerken: ['fris', 'peer', 'amandel'],
    omschrijving: 'Lichte, neutrale en frisse witte wijn voor elke dag.',
    pairsWith: ['vis-mager', 'schaaldieren', 'pasta', 'vegetarisch', 'zomers', 'aperitief'],
  },
  {
    id: 'rose',
    name: 'Rosé (droog)',
    type: 'Rosé',
    druif: 'Grenache / Cinsault',
    body: 'Licht',
    kenmerken: ['aardbei', 'fris', 'bloemig'],
    omschrijving: 'Droge, frisse rosé — de zomerse alleskunner.',
    pairsWith: ['zomers', 'vis-vet', 'gevogelte', 'vegetarisch', 'pittig', 'aperitief', 'kruidig'],
  },
  {
    id: 'champagne',
    name: 'Champagne / Cava (brut)',
    type: 'Mousserend',
    druif: 'Chardonnay / Pinot Noir',
    body: 'Licht',
    kenmerken: ['bubbels', 'frisse zuren', 'brioche'],
    omschrijving: 'Feestelijke mousserende wijn die ook prima bij eten past.',
    pairsWith: ['schaaldieren', 'vis-mager', 'aperitief', 'gefrituurd', 'zomers', 'dessert'],
  },
  {
    id: 'port',
    name: 'Port (Ruby)',
    type: 'Dessert',
    druif: 'Touriga Nacional',
    body: 'Vol',
    kenmerken: ['zoet', 'donker fruit', 'krachtig'],
    omschrijving: 'Zoete versterkte wijn voor bij kaas en chocolade.',
    pairsWith: ['dessert', 'kaas-pittig', 'chocolade'],
  },
  {
    id: 'malbec',
    name: 'Malbec',
    type: 'Rood',
    druif: 'Malbec',
    body: 'Vol',
    kenmerken: ['rijp donker fruit', 'rond', 'rokerig'],
    omschrijving: 'Sappige, donkere wijn uit Argentinië — geboren voor de grill.',
    pairsWith: ['rood-vlees', 'gegrild', 'hartig', 'kruidig'],
  },
  {
    id: 'tempranillo',
    name: 'Rioja (Tempranillo)',
    type: 'Rood',
    druif: 'Tempranillo',
    body: 'Medium tot vol',
    kenmerken: ['vanille', 'leer', 'rood fruit'],
    omschrijving: 'Spaanse klassieker met vatlagering, mooi bij tapas en lam.',
    pairsWith: ['rood-vlees', 'gevogelte', 'gegrild', 'hartig', 'kaas-pittig', 'kruidig'],
  },
  {
    id: 'nebbiolo',
    name: 'Barolo (Nebbiolo)',
    type: 'Rood',
    druif: 'Nebbiolo',
    body: 'Vol',
    kenmerken: ['stevige tannines', 'teer', 'roos', 'kers'],
    omschrijving: 'Aristocratische Italiaan met stevige structuur voor rijke gerechten.',
    pairsWith: ['rood-vlees', 'wild', 'paddenstoelen', 'kaas-pittig', 'hartig'],
  },
  {
    id: 'gamay',
    name: 'Beaujolais (Gamay)',
    type: 'Rood',
    druif: 'Gamay',
    body: 'Licht',
    kenmerken: ['sappig rood fruit', 'lage tannine', 'fris'],
    omschrijving: 'Licht en fruitig, ideaal licht gekoeld bij gevogelte en charcuterie.',
    pairsWith: ['gevogelte', 'kaas-zacht', 'pasta', 'zomers', 'vegetarisch', 'hartig'],
  },
  {
    id: 'gewurztraminer',
    name: 'Gewürztraminer',
    type: 'Wit',
    druif: 'Gewürztraminer',
    body: 'Vol',
    kenmerken: ['lychee', 'rozen', 'specerijen', 'iets zoet'],
    omschrijving: 'Aromatische, kruidige witte wijn — perfecte partner voor pittige keukens.',
    pairsWith: ['pittig', 'kruidig', 'aziatisch', 'kaas-pittig', 'gevogelte', 'aperitief'],
  },
  {
    id: 'gruner-veltliner',
    name: 'Grüner Veltliner',
    type: 'Wit',
    druif: 'Grüner Veltliner',
    body: 'Licht tot medium',
    kenmerken: ['witte peper', 'frisse zuren', 'groene kruiden'],
    omschrijving: 'Knisperende Oostenrijkse wijn, fantastisch bij groente en asperges.',
    pairsWith: ['vegetarisch', 'vis-mager', 'schaaldieren', 'zomers', 'pittig', 'aperitief'],
  },
  {
    id: 'albarino',
    name: 'Albariño',
    type: 'Wit',
    druif: 'Albariño',
    body: 'Licht',
    kenmerken: ['ziltig', 'citrus', 'witte perzik'],
    omschrijving: 'Zilte Spaanse kustwijn die smeekt om schaaldieren en zeevruchten.',
    pairsWith: ['schaaldieren', 'vis-mager', 'vis-vet', 'zomers', 'aperitief'],
  },
  {
    id: 'zinfandel',
    name: 'Zinfandel',
    type: 'Rood',
    druif: 'Zinfandel',
    body: 'Vol',
    kenmerken: ['jammy fruit', 'kruidig', 'hoge alcohol'],
    omschrijving: 'Stevige, fruitige Amerikaan die het opneemt tegen BBQ en specerijen.',
    pairsWith: ['rood-vlees', 'gegrild', 'kruidig', 'pittig', 'hartig'],
  },
  {
    id: 'viognier',
    name: 'Viognier',
    type: 'Wit',
    druif: 'Viognier',
    body: 'Vol',
    kenmerken: ['abrikoos', 'bloemig', 'rond'],
    omschrijving: 'Weelderige, aromatische witte wijn bij rijke vis en milde kerrie.',
    pairsWith: ['vis-vet', 'gevogelte', 'kruidig', 'romig', 'aziatisch'],
  },
  {
    id: 'moscato',
    name: 'Moscato d\'Asti',
    type: 'Dessert',
    druif: 'Moscato',
    body: 'Licht',
    kenmerken: ['zoet', 'bubbels', 'perzik', 'vlierbloesem'],
    omschrijving: 'Zachtzoete, lichtmousserende dessertwijn bij fruit en gebak.',
    pairsWith: ['dessert', 'zomers', 'aperitief'],
  },
];

const DISHES = [
  {
    id: 'biefstuk',
    name: 'Biefstuk met rode wijnsaus',
    keuken: 'Frans',
    ingredienten: ['rundvlees', 'boter', 'sjalot', 'rode wijn', 'tijm'],
    tags: ['rood-vlees', 'gegrild', 'hartig'],
    recipe: {
      type: 'eigen',
      porties: 2,
      tijd: '30 min',
      ingredienten: [
        '2 biefstukken (à 200 g)', '1 sjalot, fijngesneden', '150 ml rode wijn',
        '100 ml runderbouillon', '30 g koude boter', 'enkele takjes tijm',
        'zout en versgemalen peper',
      ],
      stappen: [
        'Haal de biefstuk 30 min voor het bakken uit de koelkast en dep droog.',
        'Bestrooi met zout en peper. Bak in hete boter ca. 2-3 min per kant voor medium.',
        'Laat het vlees rusten onder folie. Fruit de sjalot in dezelfde pan.',
        'Blus af met rode wijn, voeg bouillon en tijm toe en laat tot de helft inkoken.',
        'Klop de koude boter erdoor voor een glanzende saus en serveer over het vlees.',
      ],
    },
  },
  {
    id: 'wildzwijn-stoof',
    name: 'Gestoofde wildzwijn',
    keuken: 'Frans',
    ingredienten: ['wildzwijn', 'rode wijn', 'wortel', 'ui', 'jeneverbes'],
    tags: ['wild', 'rood-vlees', 'hartig'],
    recipe: {
      type: 'link',
      url: 'https://www.ah.nl/allerhande/recept/R-R1191525/wildzwijnstoof',
      bron: 'AH Allerhande',
    },
  },
  {
    id: 'coq-au-vin',
    name: 'Coq au vin',
    keuken: 'Frans',
    ingredienten: ['kip', 'rode wijn', 'spek', 'champignon', 'ui'],
    tags: ['gevogelte', 'paddenstoelen', 'hartig'],
    recipe: {
      type: 'link',
      url: 'https://www.leukerecepten.nl/recepten/coq-au-vin/',
      bron: 'Leukerecepten',
    },
  },
  {
    id: 'gegrilde-lamskotelet',
    name: 'Gegrilde lamskoteletten',
    keuken: 'Mediterraans',
    ingredienten: ['lamsvlees', 'knoflook', 'rozemarijn', 'olijfolie'],
    tags: ['rood-vlees', 'gegrild', 'kruidig'],
    recipe: {
      type: 'eigen',
      porties: 4,
      tijd: '25 min',
      ingredienten: [
        '8 lamskoteletten', '3 tenen knoflook, geplet', '2 takjes rozemarijn',
        '4 el olijfolie', 'sap van ½ citroen', 'zout en peper',
      ],
      stappen: [
        'Meng olijfolie, knoflook, fijngehakte rozemarijn en citroensap tot een marinade.',
        'Wentel de koteletten erin en laat minstens 1 uur marineren.',
        'Verhit de grill of grillpan goed heet.',
        'Gril de koteletten 2-3 min per kant; ze mogen rosé blijven van binnen.',
        'Laat kort rusten, bestrooi met zout en peper en serveer.',
      ],
    },
  },
  {
    id: 'pasta-bolognese',
    name: 'Pasta bolognese',
    keuken: 'Italiaans',
    ingredienten: ['gehakt', 'tomaat', 'ui', 'knoflook', 'pasta'],
    tags: ['pasta', 'rood-vlees', 'hartig'],
    recipe: {
      type: 'eigen',
      porties: 4,
      tijd: '45 min',
      ingredienten: [
        '400 g rundergehakt', '1 ui', '2 tenen knoflook', '1 wortel',
        '800 g tomatenblokjes', '100 ml rode wijn', '400 g spaghetti', 'Parmezaan',
      ],
      stappen: [
        'Fruit ui, knoflook en fijngesneden wortel in olijfolie.',
        'Voeg het gehakt toe en bak rul. Blus af met de rode wijn.',
        'Voeg de tomatenblokjes toe en laat minstens 30 min zachtjes pruttelen.',
        'Kook intussen de spaghetti beetgaar.',
        'Breng de saus op smaak met zout en peper en serveer met Parmezaan.',
      ],
    },
  },
  {
    id: 'margherita',
    name: 'Pizza Margherita',
    keuken: 'Italiaans',
    ingredienten: ['pizzadeeg', 'tomaat', 'mozzarella', 'basilicum'],
    tags: ['pizza', 'vegetarisch', 'hartig'],
    recipe: {
      type: 'link',
      url: 'https://www.24kitchen.nl/recepten/pizza-margherita',
      bron: '24Kitchen',
    },
  },
  {
    id: 'gegrilde-zalm',
    name: 'Gegrilde zalmfilet',
    keuken: 'Internationaal',
    ingredienten: ['zalm', 'citroen', 'dille', 'olijfolie'],
    tags: ['vis-vet', 'gegrild', 'zomers'],
    recipe: {
      type: 'eigen',
      porties: 2,
      tijd: '20 min',
      ingredienten: [
        '2 zalmfilets met huid', '1 citroen', 'verse dille', '2 el olijfolie',
        'zout en peper',
      ],
      stappen: [
        'Dep de zalm droog en bestrijk met olijfolie, zout en peper.',
        'Leg de filet met de huid naar beneden in een hete pan of op de grill.',
        'Bak 4-5 min tot de huid krokant is, keer dan kort om.',
        'Bestrooi met dille en serveer met partjes citroen.',
      ],
    },
  },
  {
    id: 'mosselen',
    name: 'Mosselen in witte wijn',
    keuken: 'Belgisch',
    ingredienten: ['mosselen', 'witte wijn', 'prei', 'ui', 'selderij'],
    tags: ['schaaldieren', 'romig'],
    recipe: {
      type: 'eigen',
      porties: 4,
      tijd: '30 min',
      ingredienten: [
        '4 kg mosselen', '250 ml droge witte wijn', '2 uien', '1 prei',
        '2 stengels bleekselderij', 'peterselie', 'klont boter',
      ],
      stappen: [
        'Spoel de mosselen en gooi open exemplaren weg.',
        'Snijd ui, prei en selderij grof en stoof aan in de boter.',
        'Voeg de mosselen en de witte wijn toe en doe de deksel op de pan.',
        'Schud de pan af en toe; na 5-7 min zijn de mosselen open en gaar.',
        'Bestrooi met peterselie en serveer met friet en brood.',
      ],
    },
  },
  {
    id: 'garnalen-knoflook',
    name: 'Gamba\'s in knoflookolie',
    keuken: 'Spaans',
    ingredienten: ['garnalen', 'knoflook', 'peterselie', 'olijfolie', 'chili'],
    tags: ['schaaldieren', 'aperitief', 'kruidig'],
    recipe: {
      type: 'eigen',
      porties: 4,
      tijd: '15 min',
      ingredienten: [
        '500 g gepelde gamba\'s', '4 tenen knoflook', '1 rode peper',
        '100 ml olijfolie', 'peterselie', 'zout',
      ],
      stappen: [
        'Verhit de olijfolie met gesneden knoflook en rode peper zachtjes.',
        'Laat de knoflook geuren maar niet bruin worden.',
        'Voeg de gamba\'s toe en bak ze in 2-3 min roze en gaar.',
        'Bestrooi met zout en peterselie en serveer met stokbrood.',
      ],
    },
  },
  {
    id: 'sushi',
    name: 'Sushi en sashimi',
    keuken: 'Japans',
    ingredienten: ['rijst', 'rauwe vis', 'nori', 'wasabi', 'sojasaus'],
    tags: ['vis-mager', 'aziatisch', 'aperitief'],
    recipe: {
      type: 'link',
      url: 'https://www.leukerecepten.nl/recepten/sushi/',
      bron: 'Leukerecepten',
    },
  },
  {
    id: 'pad-thai',
    name: 'Pad Thai met kip',
    keuken: 'Thais',
    ingredienten: ['rijstnoedels', 'kip', 'ei', 'taugé', 'pinda', 'limoen'],
    tags: ['aziatisch', 'pittig', 'gevogelte', 'kruidig'],
    recipe: {
      type: 'link',
      url: 'https://www.ah.nl/allerhande/recept/R-R1190946/pad-thai',
      bron: 'AH Allerhande',
    },
  },
  {
    id: 'groene-curry',
    name: 'Groene curry met kip',
    keuken: 'Thais',
    ingredienten: ['kip', 'kokosmelk', 'currypasta', 'aubergine', 'basilicum'],
    tags: ['aziatisch', 'pittig', 'gevogelte', 'romig', 'kruidig'],
    recipe: {
      type: 'eigen',
      porties: 4,
      tijd: '30 min',
      ingredienten: [
        '500 g kipdijfilet', '400 ml kokosmelk', '3 el groene currypasta',
        '1 aubergine', 'Thaise basilicum', 'vissaus', 'limoen',
      ],
      stappen: [
        'Bak de currypasta kort in een scheut olie tot het geurt.',
        'Voeg de in stukken gesneden kip toe en bak rondom aan.',
        'Schenk de kokosmelk erbij en voeg de aubergineblokjes toe.',
        'Laat 15 min zachtjes pruttelen tot de kip gaar is.',
        'Breng op smaak met vissaus en limoen en werk af met basilicum.',
      ],
    },
  },
  {
    id: 'kipsaté',
    name: 'Kipsaté met pindasaus',
    keuken: 'Indonesisch',
    ingredienten: ['kip', 'ketjap', 'pindakaas', 'knoflook', 'gember'],
    tags: ['gevogelte', 'pittig', 'gegrild', 'kruidig'],
    recipe: {
      type: 'link',
      url: 'https://www.ah.nl/allerhande/recept/R-R1187448/kipsate',
      bron: 'AH Allerhande',
    },
  },
  {
    id: 'risotto-paddenstoel',
    name: 'Paddenstoelenrisotto',
    keuken: 'Italiaans',
    ingredienten: ['risottorijst', 'paddenstoelen', 'witte wijn', 'parmezaan', 'bouillon'],
    tags: ['vegetarisch', 'romig', 'paddenstoelen', 'pasta'],
    recipe: {
      type: 'eigen',
      porties: 4,
      tijd: '40 min',
      ingredienten: [
        '300 g risottorijst', '400 g gemengde paddenstoelen', '150 ml witte wijn',
        '1 l groentebouillon', '1 ui', '50 g Parmezaan', 'klont boter',
      ],
      stappen: [
        'Fruit de ui glazig en bak de paddenstoelen kort mee.',
        'Voeg de rijst toe en bak 1 min mee tot glazig.',
        'Blus af met de witte wijn en laat inkoken.',
        'Voeg de warme bouillon lepel voor lepel toe, blijf roeren tot beetgaar.',
        'Roer er boter en Parmezaan door en breng op smaak.',
      ],
    },
  },
  {
    id: 'geitenkaas-salade',
    name: 'Salade met warme geitenkaas',
    keuken: 'Frans',
    ingredienten: ['geitenkaas', 'sla', 'walnoot', 'honing', 'stokbrood'],
    tags: ['vegetarisch', 'kaas-zacht', 'zomers', 'aperitief'],
    recipe: {
      type: 'eigen',
      porties: 2,
      tijd: '15 min',
      ingredienten: [
        '2 plakjes geitenkaas', 'gemengde sla', 'handje walnoten', '2 el honing',
        '4 sneetjes stokbrood', 'olijfolie en balsamico',
      ],
      stappen: [
        'Leg de geitenkaas op het stokbrood en besprenkel met honing.',
        'Gratineer kort onder de grill tot de kaas zacht is.',
        'Verdeel de sla over de borden en bestrooi met walnoten.',
        'Leg de warme geitenkaastoast erop en besprenkel met olie en balsamico.',
      ],
    },
  },
  {
    id: 'kaasplank',
    name: 'Kaasplank (oude & pittige kaas)',
    keuken: 'Internationaal',
    ingredienten: ['oude kaas', 'blauwe kaas', 'noten', 'vijgen', 'crackers'],
    tags: ['kaas-pittig', 'hartig'],
    recipe: {
      type: 'eigen',
      porties: 4,
      tijd: '10 min',
      ingredienten: [
        'oude kaas', 'blauwaderkaas', 'gemengde noten', 'verse of gedroogde vijgen',
        'crackers', 'wat honing of vijgenjam',
      ],
      stappen: [
        'Haal de kazen ruim op tijd uit de koelkast (op kamertemperatuur smaken ze beter).',
        'Snijd de kazen in punten en verdeel over een plank.',
        'Vul aan met noten, vijgen en crackers.',
        'Serveer met een beetje honing of vijgenjam.',
      ],
    },
  },
  {
    id: 'oesters',
    name: 'Verse oesters',
    keuken: 'Frans',
    ingredienten: ['oesters', 'citroen', 'sjalot', 'azijn'],
    tags: ['schaaldieren', 'aperitief', 'zomers'],
    recipe: {
      type: 'eigen',
      porties: 2,
      tijd: '10 min',
      ingredienten: [
        '12 verse oesters', '1 citroen', '1 sjalot', '2 el rodewijnazijn',
      ],
      stappen: [
        'Open de oesters voorzichtig met een oestermes.',
        'Maak een mignonette van fijngesneden sjalot en rodewijnazijn.',
        'Serveer de oesters op ijs met partjes citroen en de mignonette.',
      ],
    },
  },
  {
    id: 'chocolademousse',
    name: 'Chocolademousse',
    keuken: 'Frans',
    ingredienten: ['pure chocolade', 'ei', 'suiker', 'slagroom'],
    tags: ['dessert', 'chocolade'],
    recipe: {
      type: 'eigen',
      porties: 4,
      tijd: '20 min + koelen',
      ingredienten: [
        '200 g pure chocolade', '4 eieren', '50 g suiker', '100 ml slagroom',
      ],
      stappen: [
        'Smelt de chocolade au bain-marie en laat iets afkoelen.',
        'Splits de eieren; roer de dooiers door de chocolade.',
        'Klop de eiwitten met de suiker stijf en klop de slagroom apart op.',
        'Spatel eerst de slagroom, daarna voorzichtig de eiwitten erdoor.',
        'Verdeel over glaasjes en laat minstens 2 uur opstijven in de koelkast.',
      ],
    },
  },
  {
    id: 'appeltaart',
    name: 'Appeltaart',
    keuken: 'Nederlands',
    ingredienten: ['appel', 'bladerdeeg', 'kaneel', 'rozijnen', 'suiker'],
    tags: ['dessert', 'zomers'],
    recipe: {
      type: 'link',
      url: 'https://www.leukerecepten.nl/recepten/appeltaart/',
      bron: 'Leukerecepten',
    },
  },
  {
    id: 'gefrituurde-kibbeling',
    name: 'Kibbeling met ravigotesaus',
    keuken: 'Nederlands',
    ingredienten: ['witvis', 'bloem', 'bier', 'frituurolie'],
    tags: ['vis-mager', 'gefrituurd', 'hartig'],
    recipe: {
      type: 'eigen',
      porties: 4,
      tijd: '25 min',
      ingredienten: [
        '600 g kabeljauwhaas', '150 g bloem', '200 ml koud bier', 'paprikapoeder',
        'frituurolie', 'ravigotesaus om te serveren',
      ],
      stappen: [
        'Snijd de vis in hapklare stukken en bestrooi met zout en paprikapoeder.',
        'Maak een beslag van bloem en koud bier tot een dikke yoghurtdikte.',
        'Verhit de frituurolie tot 180 °C.',
        'Haal de visstukken door het beslag en frituur ze goudbruin in 3-4 min.',
        'Laat uitlekken op keukenpapier en serveer met ravigotesaus.',
      ],
    },
  },
  {
    id: 'boeuf-bourguignon',
    name: 'Bœuf bourguignon',
    keuken: 'Frans',
    ingredienten: ['rundvlees', 'rode wijn', 'spek', 'wortel', 'champignon', 'ui'],
    tags: ['rood-vlees', 'wild', 'paddenstoelen', 'hartig'],
    recipe: {
      type: 'eigen',
      porties: 4,
      tijd: '3 uur',
      ingredienten: [
        '800 g rundersukade in blokjes', '150 g spekblokjes', '750 ml rode bourgogne',
        '2 wortels', '250 g champignons', '2 uien', '2 el bloem', '2 tenen knoflook',
        'bouquet garni (tijm, laurier)',
      ],
      stappen: [
        'Bak de spekjes uit en braad het vlees rondom bruin in de jus.',
        'Bestrooi met bloem, schep om en bak kort mee.',
        'Voeg ui, knoflook en wortel toe en blus af met de rode wijn.',
        'Voeg het bouquet garni toe en stoof afgedekt 2,5 uur op laag vuur.',
        'Bak de champignons apart en roer ze het laatste half uur erdoor.',
        'Breng op smaak en serveer met aardappelpuree of stokbrood.',
      ],
    },
  },
  {
    id: 'carpaccio',
    name: 'Rundercarpaccio',
    keuken: 'Italiaans',
    ingredienten: ['rundvlees', 'parmezaan', 'rucola', 'pijnboompit', 'truffel'],
    tags: ['rood-vlees', 'aperitief', 'zomers', 'paddenstoelen'],
    recipe: {
      type: 'eigen',
      porties: 4,
      tijd: '15 min',
      ingredienten: [
        '300 g runderhaas (flinterdun gesneden)', '50 g Parmezaan', 'handje rucola',
        '2 el pijnboompitten', 'truffelmayonaise', 'olijfolie', 'peper en zout',
      ],
      stappen: [
        'Verdeel de plakjes rundvlees over koude borden.',
        'Bestrooi met zout, peper en een scheutje olijfolie.',
        'Verdeel rucola, geroosterde pijnboompitten en schaafsel Parmezaan erover.',
        'Werk af met dunne strepen truffelmayonaise.',
      ],
    },
  },
  {
    id: 'spareribs',
    name: 'Spareribs van de BBQ',
    keuken: 'Amerikaans',
    ingredienten: ['varkensribben', 'bbq-saus', 'paprikapoeder', 'bruine suiker', 'knoflook'],
    tags: ['rood-vlees', 'gegrild', 'kruidig', 'hartig', 'pittig'],
    recipe: {
      type: 'link',
      url: 'https://www.leukerecepten.nl/recepten/spareribs/',
      bron: 'Leukerecepten',
    },
  },
  {
    id: 'magret-eend',
    name: 'Gebakken eendenborst',
    keuken: 'Frans',
    ingredienten: ['eend', 'honing', 'sinaasappel', 'tijm'],
    tags: ['gevogelte', 'wild', 'hartig'],
    recipe: {
      type: 'eigen',
      porties: 2,
      tijd: '30 min',
      ingredienten: [
        '2 eendenborsten', '2 el honing', 'sap van 1 sinaasappel', 'takje tijm',
        'zout en peper',
      ],
      stappen: [
        'Kerf de huid van de eend ruitvormig in en bestrooi met zout.',
        'Leg de borst koud in de pan, huid naar beneden, en bak het vet langzaam uit (8-10 min).',
        'Keer om en bak nog 3-4 min; de eend mag rosé blijven.',
        'Haal uit de pan en laat rusten. Deglaceer met sinaasappelsap en honing tot siroop.',
        'Snijd de eend in plakjes en nappeer met de saus.',
      ],
    },
  },
  {
    id: 'tonijnsteak',
    name: 'Gegrilde tonijnsteak',
    keuken: 'Mediterraans',
    ingredienten: ['tonijn', 'sesam', 'sojasaus', 'limoen', 'gember'],
    tags: ['vis-vet', 'gegrild', 'aziatisch', 'zomers'],
    recipe: {
      type: 'eigen',
      porties: 2,
      tijd: '15 min',
      ingredienten: [
        '2 tonijnsteaks', '3 el sesamzaad', '2 el sojasaus', 'sap van 1 limoen',
        'stukje gember', 'sesamolie',
      ],
      stappen: [
        'Marineer de tonijn kort in sojasaus, limoen en geraspte gember.',
        'Wentel de steaks door het sesamzaad.',
        'Schroei ze in een hete pan met sesamolie 1 min per kant dicht.',
        'Snijd in plakjes; de kern blijft rauw en rozerood.',
      ],
    },
  },
  {
    id: 'paella',
    name: 'Paella met zeevruchten',
    keuken: 'Spaans',
    ingredienten: ['rijst', 'garnalen', 'mosselen', 'saffraan', 'paprika', 'kip'],
    tags: ['schaaldieren', 'gevogelte', 'kruidig', 'zomers', 'hartig'],
    recipe: {
      type: 'link',
      url: 'https://www.ah.nl/allerhande/recept/R-R1189662/paella',
      bron: 'AH Allerhande',
    },
  },
  {
    id: 'tikka-masala',
    name: 'Chicken tikka masala',
    keuken: 'Indiaas',
    ingredienten: ['kip', 'tomaat', 'room', 'garam masala', 'gember', 'knoflook'],
    tags: ['aziatisch', 'pittig', 'kruidig', 'romig', 'gevogelte'],
    recipe: {
      type: 'link',
      url: 'https://www.leukerecepten.nl/recepten/chicken-tikka-masala/',
      bron: 'Leukerecepten',
    },
  },
  {
    id: 'dahl',
    name: 'Linzen dahl',
    keuken: 'Indiaas',
    ingredienten: ['rode linzen', 'kokosmelk', 'kurkuma', 'komijn', 'spinazie'],
    tags: ['vegetarisch', 'aziatisch', 'kruidig', 'pittig', 'romig'],
    recipe: {
      type: 'eigen',
      porties: 4,
      tijd: '35 min',
      ingredienten: [
        '300 g rode linzen', '400 ml kokosmelk', '1 ui', '2 tenen knoflook',
        '1 tl kurkuma', '1 tl komijn', '100 g spinazie', 'verse koriander',
      ],
      stappen: [
        'Fruit ui en knoflook met de specerijen tot het geurt.',
        'Voeg de gespoelde linzen, kokosmelk en 300 ml water toe.',
        'Laat 20-25 min zachtjes koken tot de linzen uiteenvallen.',
        'Roer de spinazie erdoor tot geslonken en breng op smaak.',
        'Werk af met koriander en serveer met rijst of naan.',
      ],
    },
  },
  {
    id: 'lasagne',
    name: 'Lasagne al forno',
    keuken: 'Italiaans',
    ingredienten: ['gehakt', 'tomaat', 'bechamel', 'lasagnebladen', 'parmezaan'],
    tags: ['pasta', 'rood-vlees', 'romig', 'hartig'],
    recipe: {
      type: 'link',
      url: 'https://www.leukerecepten.nl/recepten/lasagne/',
      bron: 'Leukerecepten',
    },
  },
  {
    id: 'carbonara',
    name: 'Spaghetti carbonara',
    keuken: 'Italiaans',
    ingredienten: ['spaghetti', 'guanciale', 'ei', 'pecorino', 'peper'],
    tags: ['pasta', 'romig', 'hartig'],
    recipe: {
      type: 'eigen',
      porties: 2,
      tijd: '20 min',
      ingredienten: [
        '200 g spaghetti', '100 g guanciale of pancetta', '2 eidooiers + 1 ei',
        '50 g pecorino', 'versgemalen zwarte peper',
      ],
      stappen: [
        'Kook de spaghetti beetgaar en bewaar een kopje kookvocht.',
        'Bak de guanciale knapperig uit (zonder olie).',
        'Klop de eieren met de geraspte pecorino en veel peper.',
        'Meng de hete pasta met de guanciale, haal van het vuur.',
        'Roer het eimengsel erdoor met een scheut kookvocht tot een romige saus — niet laten schiften.',
      ],
    },
  },
  {
    id: 'ratatouille',
    name: 'Ratatouille',
    keuken: 'Frans',
    ingredienten: ['courgette', 'aubergine', 'paprika', 'tomaat', 'tijm', 'knoflook'],
    tags: ['vegetarisch', 'zomers', 'kruidig'],
    recipe: {
      type: 'eigen',
      porties: 4,
      tijd: '50 min',
      ingredienten: [
        '1 aubergine', '2 courgettes', '2 paprika\'s', '4 tomaten', '2 uien',
        '3 tenen knoflook', 'verse tijm', 'olijfolie',
      ],
      stappen: [
        'Snijd alle groenten in gelijke blokjes.',
        'Fruit ui en knoflook in olijfolie in een ruime pan.',
        'Voeg aubergine en paprika toe en bak 10 min.',
        'Voeg courgette en tomaat met tijm toe en stoof 25 min op laag vuur.',
        'Breng op smaak met zout en peper; lekker warm én koud.',
      ],
    },
  },
  {
    id: 'tagine',
    name: 'Lamstagine met abrikoos',
    keuken: 'Marokkaans',
    ingredienten: ['lamsvlees', 'abrikoos', 'kaneel', 'komijn', 'amandel', 'ui'],
    tags: ['rood-vlees', 'kruidig', 'hartig'],
    recipe: {
      type: 'link',
      url: 'https://www.ah.nl/allerhande/recept/R-R1188436/lamstagine',
      bron: 'AH Allerhande',
    },
  },
  {
    id: 'nasi-goreng',
    name: 'Nasi goreng',
    keuken: 'Indonesisch',
    ingredienten: ['rijst', 'kip', 'ei', 'sambal', 'ketjap', 'ui'],
    tags: ['aziatisch', 'pittig', 'gevogelte', 'kruidig', 'hartig'],
    recipe: {
      type: 'eigen',
      porties: 4,
      tijd: '30 min',
      ingredienten: [
        '300 g rijst (gekookt en koud)', '300 g kipfilet', '2 eieren', '1 el sambal',
        '3 el ketjap manis', '1 ui', '2 tenen knoflook', 'bosui',
      ],
      stappen: [
        'Bak de in reepjes gesneden kip gaar en houd apart.',
        'Fruit ui, knoflook en sambal in een wok.',
        'Voeg de koude rijst toe en bak al roerend goed warm.',
        'Schep de kip en ketjap erdoor.',
        'Bak van de eieren roerei en meng dit erdoor; werk af met bosui.',
      ],
    },
  },
  {
    id: 'crème-brulee',
    name: 'Crème brûlée',
    keuken: 'Frans',
    ingredienten: ['room', 'eidooier', 'vanille', 'suiker'],
    tags: ['dessert', 'romig'],
    recipe: {
      type: 'eigen',
      porties: 4,
      tijd: '40 min + koelen',
      ingredienten: [
        '500 ml slagroom', '5 eidooiers', '80 g suiker', '1 vanillestokje',
        'rietsuiker om te karamelliseren',
      ],
      stappen: [
        'Verwarm de room met het opengesneden vanillestokje tegen de kook aan.',
        'Klop de dooiers met de suiker luchtig en schenk de warme room erbij.',
        'Verdeel over ovenschaaltjes en bak au bain-marie 35 min op 150 °C.',
        'Laat afkoelen en minstens 3 uur opstijven in de koelkast.',
        'Bestrooi met rietsuiker en brand af met een brander tot een krokant laagje.',
      ],
    },
  },
  {
    id: 'tiramisu',
    name: 'Tiramisù',
    keuken: 'Italiaans',
    ingredienten: ['mascarpone', 'koffie', 'lange vingers', 'ei', 'cacao'],
    tags: ['dessert', 'romig'],
    recipe: {
      type: 'link',
      url: 'https://www.leukerecepten.nl/recepten/tiramisu/',
      bron: 'Leukerecepten',
    },
  },
  {
    id: 'kaasfondue',
    name: 'Kaasfondue',
    keuken: 'Zwitsers',
    ingredienten: ['gruyère', 'emmentaler', 'witte wijn', 'knoflook', 'stokbrood'],
    tags: ['kaas-pittig', 'romig', 'hartig'],
    recipe: {
      type: 'eigen',
      porties: 4,
      tijd: '25 min',
      ingredienten: [
        '400 g Gruyère', '400 g Emmentaler', '300 ml droge witte wijn', '1 teen knoflook',
        '1 el maïzena', 'scheutje kirsch', 'stokbrood in blokjes',
      ],
      stappen: [
        'Wrijf de fonduepan in met de gehalveerde knoflook.',
        'Verwarm de wijn en laat de geraspte kaas al roerend smelten.',
        'Roer de maïzena met de kirsch glad en meng erdoor tot gebonden.',
        'Houd warm op het rechaud en doop er stukjes brood in.',
      ],
    },
  },
  {
    id: 'gegrilde-groenten',
    name: 'Gegrilde mediterrane groenten',
    keuken: 'Mediterraans',
    ingredienten: ['courgette', 'paprika', 'aubergine', 'olijfolie', 'balsamico'],
    tags: ['vegetarisch', 'gegrild', 'zomers'],
    recipe: {
      type: 'eigen',
      porties: 4,
      tijd: '25 min',
      ingredienten: [
        '1 courgette', '1 aubergine', '2 paprika\'s', '1 rode ui', 'olijfolie',
        'balsamico', 'verse basilicum',
      ],
      stappen: [
        'Snijd de groenten in plakken en bestrijk met olijfolie, zout en peper.',
        'Gril ze om en om tot ze mooie grillstrepen en beet hebben.',
        'Schik op een schaal en besprenkel met balsamico.',
        'Werk af met gescheurde basilicum; lekker warm of lauw.',
      ],
    },
  },
];

// Vrije-tekst trefwoorden per pairing tag, zodat zoeken op ingrediënt of
// keuken ook werkt (bijv. "pittig", "vis", "kaas").
const TAG_KEYWORDS = {
  'rood-vlees': ['rood vlees', 'rundvlees', 'biefstuk', 'lam', 'steak', 'entrecote', 'rund'],
  'gevogelte': ['kip', 'gevogelte', 'kalkoen', 'eend', 'gevogel'],
  'wild': ['wild', 'hert', 'zwijn', 'haas', 'fazant'],
  'vis-mager': ['witvis', 'kabeljauw', 'tong', 'magere vis', 'sushi', 'vis'],
  'vis-vet': ['zalm', 'tonijn', 'makreel', 'vette vis', 'vis'],
  'schaaldieren': ['garnalen', 'gamba', 'mosselen', 'oesters', 'kreeft', 'schaaldieren', 'zeevruchten'],
  'kaas-zacht': ['zachte kaas', 'geitenkaas', 'brie', 'mozzarella', 'kaas'],
  'kaas-pittig': ['oude kaas', 'blauwe kaas', 'pittige kaas', 'belegen', 'kaas'],
  'pasta': ['pasta', 'spaghetti', 'risotto', 'noedels'],
  'pizza': ['pizza'],
  'pittig': ['pittig', 'pikant', 'chili', 'spicy', 'heet'],
  'kruidig': ['kruidig', 'specerijen', 'kerrie', 'curry'],
  'romig': ['romig', 'room', 'saus', 'kokos'],
  'gegrild': ['gegrild', 'bbq', 'barbecue', 'grill'],
  'vegetarisch': ['vegetarisch', 'veggie', 'groente'],
  'dessert': ['dessert', 'toetje', 'zoet', 'nagerecht'],
  'aperitief': ['aperitief', 'borrel', 'hapje'],
  'zomers': ['zomers', 'salade', 'fris'],
  'hartig': ['hartig', 'stoof'],
  'aziatisch': ['aziatisch', 'thais', 'japans', 'chinees', 'indonesisch', 'azie', 'indiaas', 'indian', 'india', 'curry', 'sushi', 'wok'],
  'paddenstoelen': ['paddenstoel', 'champignon', 'truffel'],
  'gefrituurd': ['gefrituurd', 'frituur', 'kibbeling', 'gebakken'],
  'chocolade': ['chocolade', 'choco'],
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { WINES, DISHES, TAG_KEYWORDS };
} else if (typeof window !== 'undefined') {
  window.WINES = WINES;
  window.DISHES = DISHES;
  window.TAG_KEYWORDS = TAG_KEYWORDS;
}
